# Generated by Django 3.2.4 on 2021-07-08 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency_type', models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Twice', 'Twice'), ('Minute', 'Minute'), ('Second', 'Second'), ('10Second', 'Second')], max_length=20, null=True)),
                ('repetition_count', models.IntegerField(default=0)),
                ('max_frequency', models.IntegerField(default=0)),
                ('scheduled_date', models.DateTimeField(null=True)),
                ('content', models.CharField(max_length=75, null=True)),
                ('is_repetitive', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
