# Generated by Django 3.2.4 on 2021-07-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
