# Generated by Django 3.2.4 on 2021-06-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_in', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_in', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_in', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_in', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_in', models.CharField(max_length=100)),
                ('up_date', models.DateField(blank=True, null=True)),
                ('contact_out', models.ManyToManyField(blank=True, to='billboard.Contact')),
                ('email_out', models.ManyToManyField(blank=True, to='billboard.Email')),
                ('social_out', models.ManyToManyField(blank=True, to='billboard.Social')),
                ('subject_out', models.ManyToManyField(blank=True, to='billboard.Subject')),
            ],
        ),
    ]
