# Generated by Django 2.2.18 on 2021-06-26 23:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardModels',
            new_name='Board',
        ),
    ]
