# Generated by Django 2.2.18 on 2021-06-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_auto_20210627_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='admin',
        ),
        migrations.AlterField(
            model_name='board',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='social',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
