# Generated by Django 2.2.18 on 2021-06-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0004_auto_20210627_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='published_date',
            new_name='up_date',
        ),
        migrations.AlterField(
            model_name='professor',
            name='contact_out',
            field=models.ManyToManyField(blank=True, to='billboard.Contact'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email_out',
            field=models.ManyToManyField(blank=True, to='billboard.Email'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='social_out',
            field=models.ManyToManyField(blank=True, to='billboard.Social'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='subject_out',
            field=models.ManyToManyField(blank=True, to='billboard.Subject'),
        ),
    ]
