# Generated by Django 2.2.18 on 2021-06-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0007_auto_20210627_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_out',
            new_name='subject_in',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='professor_out',
        ),
        migrations.AddField(
            model_name='professor',
            name='subject_out',
            field=models.ManyToManyField(blank=True, to='billboard.Subject'),
        ),
    ]
