# Generated by Django 2.2.18 on 2021-06-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0009_auto_20210627_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_in',
            field=models.CharField(max_length=100),
        ),
    ]
